### ISSUE TITLE
Cannot run scripts

### ISSUE THREAD

**Issue by Rdornier** [Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO#5]
Hello @TorecLuik, 

I would like first to thank you for this great job you did ; it fills the gap between storage database and processing unit.
We are interested to implement workflows using BIOMERO. In order to try it out locally, I follow the [Quickstart ](https://github.com/Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO?tab=readme-ov-file#quickstart) tutorial, which works well. I am able to import data on the local OMERO and can browse the BIOMERO scripts.
However, I am not able to run them.

When I run the `slurm/init/SLURM Init environment...` from OMERO web, it gives me the follwing error message. If I try to run the other scripts, I get a `Server Error 500` .
```

Traceback (most recent call last):
  File "/opt/omero/server/omero/tmp/omero_omero-server/172/process3mbxhckh.dir/./script", line 64, in <module>
    runScript()
  File "/opt/omero/server/omero/tmp/omero_omero-server/172/process3mbxhckh.dir/./script", line 50, in runScript
    with SlurmClient.from_config(configfile=configfile,
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/biomero/slurm_client.py", line 471, in from_config
    return cls(host=host,
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/biomero/slurm_client.py", line 239, in __init__
    self.validate(validate_slurm_setup=init_slurm)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/biomero/slurm_client.py", line 549, in validate
    connected = self.run('echo " "').ok
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
```

Server Error 500
```
Traceback (most recent call last):

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/omeroweb/decorators.py", line 538, in wrapped
    retval = f(request, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/omeroweb/decorators.py", line 597, in wrapper
    context = f(request, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/omeroweb/webclient/views.py", line 4126, in script_ui
    raise ex

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/omeroweb/webclient/views.py", line 4119, in script_ui
    params = scriptService.getParams(long(scriptId))

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/omero/gateway/__init__.py", line 4859, in __call__
    return self.handle_exception(e, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/omeroweb/webclient/webclient_gateway.py", line 2123, in handle_exception
    super(OmeroWebSafeCallWrapper, self).handle_exception(e, *args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/omero/gateway/__init__.py", line 4856, in __call__
    return self.f(*args, **kwargs)

  File "/opt/omero/web/venv3/lib64/python3.9/site-packages/omero_api_IScript_ice.py", line 842, in getParams
    return _M_omero.api.IScript._op_getParams.invoke(self, ((scriptID, ), _ctx))

omero.ValidationException: exception ::omero::ValidationException
{
    serverStackTrace = 
    serverExceptionClass = 
    message = Can't find params for 66!
No stdout.
stderr is in file 236:
---------------------------------
Traceback (most recent call last):
  File "/opt/omero/server/omero/tmp/omero_omero-server/172/processk9bfihi6.dir/./script", line 729, in <module>
    runScript()
  File "/opt/omero/server/omero/tmp/omero_omero-server/172/processk9bfihi6.dir/./script", line 96, in runScript
    with SlurmClient.from_config() as slurmClient:
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/biomero/slurm_client.py", line 471, in from_config
    return cls(host=host,
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/biomero/slurm_client.py", line 239, in __init__
    self.validate(validate_slurm_setup=init_slurm)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/biomero/slurm_client.py", line 549, in validate
    connected = self.run('echo " "').ok
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/fabric/connection.py", line 22, in opens
    self.open()
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/fabric/connection.py", line 665, in open
    result = self.client.connect(**kwargs)
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/paramiko/client.py", line 377, in connect
    to_try = list(self._families_and_addresses(hostname, port))
  File "/opt/omero/server/venv3/lib64/python3.9/site-packages/paramiko/client.py", line 202, in _families_and_addresses
    addrinfos = socket.getaddrinfo(
  File "/usr/lib64/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

---------------------------------

}
```

Do you know what causes this issue ? I must say that I do not have access to the SLURM servers of our institut and I performed this test on my workstation, with two docker containers (nl-biomero and slurm-docker-cluster), installed from the previous steps.

Many thanks and all the best,
Rémy.

**Comment by TorecLuik** [comment]
Hey Rémy, thanks for testing it out.

To get started, what is your OS / docker / workstation setup running this?

It def sounds like a communication issue between the 2 clusters, which we personally haven't run into yet.

**Comment by Rdornier** [comment]
Hello  @TorecLuik, 

I'm running on Windows 11, with docker desktop 4.27.2 and WSL (Ubuntu 20.04).

I try first to ssh from the `omeroworker-processor-1` (part of  `nl-biomero` compose) with the IP address and the server name of the `slurmctld` container (part of the `slurm-docker-cluster`)  but both give me the same error, that is apparently expected.

```
bash-5.1$ ssh slurm@host.docker.internal:2222
ssh: Could not resolve hostname host.docker.internal:2222: Name or service not known
```

I'm not completely aware of all the IT stuff behind the docker logic but I was wondering how it is possible to make 2 different docker-compose communicate together (I'm a beginner in the docker field).

Also, I tried to connect to the slurm docker cluster from my machine directly. The connection was established but the file `lolcow.log` cannot be retrieved. It seems to be out of the scope but I'm wondering if it could be linked to the current issue.

```
ssh -i ~/.ssh/id_rsa -p 2222 -o StrictHostKeyChecking=no slurm@host.docker.internal
[slurm@slurmctld data]$ tail -f lolcow.log
tail: cannot open 'lolcow.log' for reading: No such file or directory
tail: no files remaining
```

Best,
Rémy.

**Comment by TorecLuik** [comment]
Hey @Rdornier,

> Also, I tried to connect to the slurm docker cluster from my machine directly. The connection was established but the file lolcow.log cannot be retrieved. It seems to be out of the scope but I'm wondering if it could be linked to the current issue.

Ok that is a good sign and should narrow it down. 
By the way, your missing lolcow.log makes sense, since you didn't run the slurm job yet 
`sbatch -n 1 --wrap "hostname > lolcow.log && singularity run docker://godlovedc/lolcow >> lolcow.log"`
The log is the result of the slurm job.

This means your Local Slurm cluster is setup properly

There is just an issue with the (BI)OMERO cluster setup. We'll have to figure out where the setup is lacking information.

There are 3 parts to this:

1. We need a ssh config file on your host machine to configure the ssh alias (at `~/.ssh/config`)
2. Your (BI)OMERO cluster should mount your SSH files into the processor node
3. Your BIOMERO library should have this slurm-config that tells it to use this ssh alias from step 1

I would wager the issue is with nr 1, because I cannot really find the instructions for this (outside of BIOMERO documentation itself)? 
See https://nl-bioimaging.github.io/biomero/readme_link.html#getting-started (point 2)

This: 
`ssh -i ~/.ssh/id_rsa -p 2222 -o StrictHostKeyChecking=no slurm@host.docker.internal`
Should be the same as 
`ssh localslurm` (as in, we create an alias 'localslurm' for this whole authentication)

You do this by creating a file called ~/.ssh/config with the alias definition inside, like this example file: https://github.com/Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO/blob/master/ssh.config.example

The details should be what you used in your initial SSH call, so:

```
Host localslurm
        HostName host.docker.internal
        User slurm
        Port 2222
        IdentityFile ~/.ssh/id_rsa
        StrictHostKeyChecking no
```



This should allow the OMERO (processor) container to also `ssh localslurm` into the slurm-docker-cluster (since we mount the same SSH files as the host machine in the docker-compose file: `- "~/.ssh:/tmp/.ssh:ro"`).
And that is exactly what the BIOMERO library is trying to do.

**Comment by Rdornier** [comment]
Thank you for the additional information ; it is helpful.

> By the way, your missing lolcow.log makes sense, since you didn't run the slurm job yet
> ``sbatch -n 1 --wrap "hostname > lolcow.log && singularity run docker://godlovedc/lolcow >> lolcow.log"``
> The log is the result of the slurm job.

Ok, with the additional command, it works !

I set the `ssh.config.example` with the same details and run `cp ssh.config.example ~/.ssh/config`.

> This:
> ``ssh -i ~/.ssh/id_rsa -p 2222 -o StrictHostKeyChecking=no slurm@host.docker.internal``
> Should be the same as
> ``ssh localslurm`` (as in, we create an alias 'localslurm' for this whole authentication)

Then, both commands work if I run them from my machine. However, only the first one works on the OMERO (processor) container terminal (``ssh localslurm`` didn't work). I don't understand why for the moment.

I saw under [Slurm Specifics](https://github.com/Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO?tab=readme-ov-file#slurm-specifics) that paths should be configured if we used a 'real' Slurm cluster, which makes sense. But do I have to configure them as well for docker ? If yes, what are the path ?

**Comment by TorecLuik** [comment]
Hey @Rdornier 

> Ok, with the additional command, it works !
> Then, both commands work if I run them from my machine

Great!

>  However, only the first one works on the OMERO (processor) container terminal (ssh localslurm didn't work). I don't understand why for the moment.

I think you need to restart the container still. Did you try that?

I didn't explain it, but there is a slight extra step that the container does at startup ( https://github.com/Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO/blob/master/worker-processor/10-mount-ssh.sh ), which is copying the mounted SSH files to a new location. This was required for technical reasons on windows docker, instead of mounting directly in the right spot. However, this means that the mounted data is not automatically updated in the right location. 
Only when the container is started it runs this 10-mount-ssh script. 
So that is my guess why one works for you and the other does not.

`docker compose down` followed by `docker compose up -d --build` should do the trick. 
Or you can restart only omeroworker-processor-1:
`docker compose down omeroworker-processor` followed by `docker compose up -d --build omeroworker-processor`

```
...
2024-02-20 16:59:08 Running /startup/10-mount-ssh.sh   <-------------------------------
2024-02-20 16:59:08 Running /startup/50-config.py 
2024-02-20 16:59:11 OpenSSL 3.0.7 1 Nov 2022 (Library: OpenSSL 3.0.7 1 Nov 2022)
2024-02-20 16:59:11 certificates created: /OMERO/certs/server.pem /OMERO/certs/server.p12
2024-02-20 16:59:15 Running /startup/99-run.sh 
2024-02-20 16:59:15 Master addr: 172.19.0.4 Worker addr: 172.19.0.3
2024-02-20 16:59:15 Starting node omeroworker-processor
```

> I saw under [Slurm Specifics](https://github.com/Cellular-Imaging-Amsterdam-UMC/NL-BIOMERO?tab=readme-ov-file#slurm-specifics) that paths should be configured if we used a 'real' Slurm cluster, which makes sense. But do I have to configure them as well for docker ? If yes, what are the path ?

No the default will work fine.

**Comment by TorecLuik** [comment]
👍 

> As a suggestion, I would also add in the QuickStart section of the Readme what should be the content of the ssh-config-example (like you did in your second post). It might help beginners like me.

Good plan. I did just update the actual content of the file to this default setting because that makes more sense anyway haha (but you'd have to git pull if you already cloned it before, etc.).
